[package]
name = "stm32h7xx-hal"
version = "0.5.0"
authors = ["Andrew Straw <strawman@astraw.com>",
           "Richard Meadows <richard@richard.fish>",
           "Henrik Böving <hargonix@gmail.com>",
           "Jan Adä <jan.adae@outlook.de>",
           "Robert Jördens <rj@quartiq.de>",
           "Florian Jung <flo@windfisch.org>"]
edition = "2018"
categories = ["embedded", "hardware-support", "no-std"]
description = "Hardware Abstraction Layer implementation for STM32H7 series microcontrollers"
keywords = ["arm", "cortex-m", "stm32h7xx", "hal", "embedded-hal"]
license = "0BSD"
repository = "https://github.com/stm32-rs/stm32h7xx-hal"
documentation = "https://docs.rs/stm32h7xx-hal"
readme = "README.md"
exclude = [".gitignore"]

[package.metadata.docs.rs]
features = ["stm32h743", "rt"]
targets = ["thumbv7em-none-eabihf"]

[dependencies]
embedded-hal = "0.2.3"
cortex-m = "^0.6.0"
cortex-m-rt = "0.6.10"
void = { version = "1.0.2", default-features = false }
cast = { version = "0.2.2", default-features = false }
nb = "0.1.2"
paste = "0.1.10"

[dependencies.stm32h7]
git = "https://github.com/stm32-rs/stm32-rs-nightlies"

[dependencies.bare-metal]
version = "0.2.4"
features = ["const-fn"]

[dev-dependencies]
panic-itm = "~0.4.1"
cortex-m-rtfm = "0.5.1"
cortex-m-log = { version = "~0.6", features = ["itm"] }

[features]
default = ["unproven"]
unproven = ["embedded-hal/unproven"]
device-selected = []
revision_v = []
singlecore = []
dualcore = []
dsi = []
cm4 = []
cm7 = []
rt = ["stm32h7/rt"]
stm32h742 = ["stm32h7/stm32h743", "device-selected", "singlecore"]
stm32h743 = ["stm32h7/stm32h743", "device-selected", "singlecore"]
stm32h753 = ["stm32h7/stm32h753", "device-selected", "singlecore"]
stm32h750 = ["stm32h7/stm32h743", "device-selected", "singlecore"]
stm32h742v = ["stm32h7/stm32h743v", "device-selected", "revision_v", "singlecore"]
stm32h743v = ["stm32h7/stm32h743v", "device-selected", "revision_v", "singlecore"]
stm32h753v = ["stm32h7/stm32h753v", "device-selected", "revision_v", "singlecore"]
stm32h750v = ["stm32h7/stm32h743v", "device-selected", "revision_v", "singlecore"]
stm32h747cm7 = ["stm32h7/stm32h747cm7", "device-selected", "revision_v", "dualcore", "cm7", "dsi"]
stm32h7b3 = ["stm32h7/stm32h7b3", "device-selected", "singlecore"]


[profile.dev]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size in flash
incremental = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size in flash
lto = true # better optimizations
opt-level = "s" # optimize for binary size

[[example]]
name = "rtfm"
required-features = ["rt"]

[[example]]
name = "rtfm_timers"
required-features = ["rt"]
